version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: recall-dev-db
    environment:
      POSTGRES_DB: recall-dev
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: recall-dev-app
    environment:
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recall-dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: 